[phases.setup]
nixPkgs = ["php", "composer", "nodejs"]

[phases.setup.commands]
# Instalamos pnpm globalmente desde npm
install_pnpm = "npm install -g pnpm"

[phases.install]
commands = ["composer install", "pnpm install"]

[phases.build]
commands = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan migrate --force"
]
