[phases.setup]
nixPkgs = ["php", "nodejs", "phpPackages.composer", "pnpm"]

[phases.install]
commands = [
  "composer install",
  "pnpm install"
]

[phases.build]
commands = [
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan migrate --force"
]
